
package InterfazG;

import Modelo.DataBaseSegura;
import Modelo.Propietario;
import Modelo.Vehículo;
import controlador.MyError;
import javax.swing.JFrame;

/**
 *
 * @author Jhosep Joel Mendoza Lazo
 */
public class VentanaAñadirVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAñadirVehiculo
     */
    JFrame padre;
    Vehículo a;
    Propietario p;
    /**
     * Constructor
     * @param padre recibe un JFrame padre 
     * inicializa un nuevo objeto de la clase padre
     */
    public VentanaAñadirVehiculo(JFrame padre) {
        a = new Vehículo();
        this.padre = padre;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPropietario = new javax.swing.JTextField();
        tfMatricula = new javax.swing.JTextField();
        tfModelo = new javax.swing.JTextField();
        tfAnio = new javax.swing.JTextField();
        jbAnadir = new javax.swing.JButton();
        jbVover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Añadir Vehiculo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Añadir Vehiculo");

        jLabel2.setText("INGRESE EL DNI DEL PROPIETARIO: ");

        jLabel3.setText("MATRICULA: ");

        jLabel4.setText("MODELO: ");

        jLabel5.setText("AÑO: ");

        tfPropietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPropietarioFocusLost(evt);
            }
        });

        tfMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMatriculaFocusLost(evt);
            }
        });

        tfModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfModeloFocusLost(evt);
            }
        });

        tfAnio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAnioFocusLost(evt);
            }
        });

        jbAnadir.setText("AÑADIR");
        jbAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnadirActionPerformed(evt);
            }
        });

        jbVover.setText("VOLVER");
        jbVover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jbAnadir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbVover)
                            .addComponent(tfPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAnadir)
                    .addComponent(jbVover))
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        //Cuando se esta cerrando hace visible la ventana de JFrame padre
        padre.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jbVoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoverActionPerformed
        //Cuando se esta cerrando hace visible la ventana de JFrame padre
        padre.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jbVoverActionPerformed

    private void tfPropietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPropietarioFocusLost

    }//GEN-LAST:event_tfPropietarioFocusLost

    private void tfMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMatriculaFocusLost

    }//GEN-LAST:event_tfMatriculaFocusLost

    private void tfModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfModeloFocusLost

    }//GEN-LAST:event_tfModeloFocusLost

    private void tfAnioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAnioFocusLost

    }//GEN-LAST:event_tfAnioFocusLost

    private void jbAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnadirActionPerformed
        try {
           /**
            * Este boton comprueba que sean metido caracteres en el JTextFiel para luego buscar al propietario mediante este si 
            * no lo encuentra lanzara el error guardado en el Metodo busca propitario si lo encuentra guardara comprovando 
            * todos los Setters de las variables de propietario en la base de datos y luego limpiara la pantalla
            */
                String dni = tfPropietario.getText();
                if (dni.length() > 0) {
                    try {
                        p = DataBaseSegura.buscaPropietario(dni);
                    } catch (MyError ex) {
                        VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
                    }
                    if (p == null) {
                        VentanaNotificaciones.ventanaError("DNI INEXISTENTE", this);
                    } else {
                        VentanaNotificaciones.ventanaOK("PROPIETARIO ENCONTRADO", padre);
                        a.setMatricula(tfMatricula.getText());
                        a.setModelo(tfModelo.getText());
                        a.setAnio(tfAnio.getText());
                        a.setPropietario(p.getDni());
                        DataBaseSegura.guardaVehiculo(a);
                        VentanaNotificaciones.ventanaOK("ALTA CORRECTA", padre);
                        limpiaPalla();
                        try {
                            a.setPropietario(dni);
                        } catch (MyError ex) {
                            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
                        }
                    }     
            } else {
                VentanaNotificaciones.ventanaError("ERROR AL INTRODUCIR LOS DATOS", padre);
            }
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
        }
    }//GEN-LAST:event_jbAnadirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAnadir;
    private javax.swing.JButton jbVover;
    private javax.swing.JTextField tfAnio;
    private javax.swing.JTextField tfMatricula;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfPropietario;
    // End of variables declaration//GEN-END:variables
    /**
     * Limpia todos los Setters e inicializa a un nuevo vehiculo y propietario
     */
    private void limpiaPalla() {
        tfAnio.setText("");
        tfMatricula.setText("");
        tfModelo.setText("");
        tfPropietario.setText("");
        a = new Vehículo();
        p = new Propietario();
    }
}
