/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazG;

import Modelo.DataBaseSegura;
import Modelo.Propietario;
import controlador.MyError;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alumno
 */
public class VentanaListaPropietarios extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListaPropietarios
     */
    JFrame padre;
    ArrayList<Propietario> listaProp;
    ArrayList<String> listaProvin;

    public VentanaListaPropietarios(JFrame padre, ArrayList<Propietario> propie) {
        this.listaProp = propie;
        this.padre = padre;
        setVisible(true);
        // Obtener las provincias de BBD
        /* misProvincias.add("Zaragoza");
          misProvincias.add("Huesca");
            misProvincias.add("Teruel");
        datos = new ComboBoxModel(misProvincias);*/
        initComponents();
        rellenaTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLista = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbVolver = new javax.swing.JButton();
        tfProvincia = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        jbProvincia = new javax.swing.JButton();
        jbNumero = new javax.swing.JButton();
        jbDos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Propietarios");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("LISTA PROPIETARIOS");

        jtLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "NOMBRE", "APELLIDO", "TELEFONO", "PROVINCIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtLista);

        jLabel2.setText("PROVINCIA");

        jLabel3.setText("NUMERO");

        jbVolver.setText("VOLVER");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jbProvincia.setText("Filtrar Provincia");
        jbProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProvinciaActionPerformed(evt);
            }
        });

        jbNumero.setText("Filtrar Numero");
        jbNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNumeroActionPerformed(evt);
            }
        });

        jbDos.setText("Filtrar por los dos ");
        jbDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jbVolver))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbProvincia)
                                            .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbNumero)
                                    .addComponent(jLabel3))
                                .addGap(40, 40, 40))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbDos)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbProvincia)
                    .addComponent(jbNumero))
                .addGap(18, 18, 18)
                .addComponent(jbDos)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jbVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        padre.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        padre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProvinciaActionPerformed
        try {
            limpiaTabla();
            listaProp = DataBaseSegura.listaPropietariosProvincia(tfProvincia.getText());
            rellenaTabla();
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);

        }
    }//GEN-LAST:event_jbProvinciaActionPerformed


    private void jbNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNumeroActionPerformed
        try {
            limpiaTabla();
            listaProp = DataBaseSegura.listaPropietariosNumeroDeCoches(Integer.parseInt(tfNumero.getText()));
            rellenaTabla();
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
        } catch (NumberFormatException e) {
            VentanaNotificaciones.ventanaError("Numero mal ingresado", padre);
        }
    }//GEN-LAST:event_jbNumeroActionPerformed

    private void jbDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDosActionPerformed
        try {
            limpiaTabla();
            listaProp = DataBaseSegura.listaPropietarios(tfProvincia.getText(), Integer.parseInt(tfNumero.getText()));
            rellenaTabla();
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
        } catch (NumberFormatException s) {
            VentanaNotificaciones.ventanaError("ERROR AL INGRESAR EL NUMERO O LA PROVINCIA", padre);
        }
    }//GEN-LAST:event_jbDosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbDos;
    private javax.swing.JButton jbNumero;
    private javax.swing.JButton jbProvincia;
    private javax.swing.JButton jbVolver;
    private javax.swing.JTable jtLista;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfProvincia;
    // End of variables declaration//GEN-END:variables

    private void rellenaTabla() {
        DefaultTableModel tablaP = (DefaultTableModel) jtLista.getModel();
        for (Propietario p : listaProp) {
            System.err.println(p.getDni());
            tablaP.addRow(p.toArray());
        }
    }

    private void limpiaTabla() {
        DefaultTableModel tablaP = (DefaultTableModel) jtLista.getModel();
        while (tablaP.getRowCount() >= 1) {
            tablaP.removeRow(0);
        }
    }

//    private String[] creaModeloComoboNumeros() {
//        try {
//            ArrayList numeros;
//            numeros = DataBaseSegura.numeroDeCoches();
//            int n = numeros.size();
//            String[] numero = new String[n];
//            for (int i = 0; i < n; i++) {
//                System.out.println(i);
//                numero[i] = numeros.get(i).toString();
//            }
//            return numero;
//        } catch (MyError ex) {
//            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
//            return null;
//        }
//    }

//    private String[] creaModeloComobo() {
//        try {
//            ArrayList ciudades = DataBaseSegura.provincias();
//            int n = ciudades.size();
//            String[] nombres = new String[n];
//            for (int i = 0; i < n; i++) {
//                Propietario p = (Propietario) ciudades.get(i);
//                System.out.println(p.getProvincia());
//                nombres[i] = p.getProvincia();
//            }
//            return nombres;
//        } catch (MyError ex) {
//            VentanaNotificaciones.ventanaError("ERROR", padre);
//            return null;
//        }
//    }

}
