/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazG;

import Modelo.DataBaseSegura;
import Modelo.Propietario;
import Modelo.Vehiculo;
import controlador.MyError;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhosep Joel Mendoza Lazo
 */
public class VentanaBajaPropietario extends javax.swing.JFrame {

    /**
     * Creates new form VentanaBajaPropietario
     */
    JFrame padre;
    Propietario p;
    ArrayList<Vehiculo> listaVehiculos;
    int n = 0, j = 0;
    boolean flag = false;
    /**
     * 
     * @param padre recive el JFrame de la ventana principal 
     */
    public VentanaBajaPropietario(JFrame padre) {
        this.padre = padre;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jfDni = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApeliido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        tfProvincia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTablaVehiculos = new javax.swing.JTable();
        jbEliminarProp = new javax.swing.JButton();
        jbElimVehi = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baja Propietario");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("BAJA PROPIETARIO");

        jLabel2.setText("Ingrese el DNI: ");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("APELLIDO:");

        jLabel5.setText("PROVINCIA");

        jLabel6.setText("TELEFONO:");

        jfDni.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jfDniFocusLost(evt);
            }
        });

        tfNombre.setEnabled(false);

        tfApeliido.setEnabled(false);

        tfTelefono.setEnabled(false);

        tfProvincia.setEnabled(false);

        jtTablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Modelo", "Año", "Propietario"
            }
        ));
        jScrollPane2.setViewportView(jtTablaVehiculos);

        jbEliminarProp.setText("Eliminar Propietario");
        jbEliminarProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarPropActionPerformed(evt);
            }
        });

        jbElimVehi.setText("Eliminar Vehiculos");
        jbElimVehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbElimVehiActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbVolver.setText("VOLVER");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jfDni)
                            .addComponent(tfNombre)
                            .addComponent(tfApeliido)
                            .addComponent(tfTelefono)
                            .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jbEliminarProp)
                        .addGap(34, 34, 34)
                        .addComponent(jbElimVehi)
                        .addGap(42, 42, 42)
                        .addComponent(jbCancelar)
                        .addGap(33, 33, 33)
                        .addComponent(jbVolver)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfApeliido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEliminarProp)
                    .addComponent(jbElimVehi)
                    .addComponent(jbCancelar)
                    .addComponent(jbVolver))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jfDniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jfDniFocusLost
        try {
            /**
             * Comprueba que el dni introducido en el primer JTextFiel exista luego agrega a esos valores al objeto inicizalizado, por ultimo 
             * rellena los otros JTextField con sus datos si no habria ningun propietario con ese DNI lanzara un mensaje si habria algun error en 
             * el metodo de la base de datos lanzara el error guardado.
             */
            p = DataBaseSegura.buscaPropietario(jfDni.getText());
            if (p != null) {
                limpiaTabla();
                tfNombre.setText(p.getNombre());
                tfApeliido.setText(p.getApellido());
                tfTelefono.setText(p.getTelefono());
                tfProvincia.setText(p.getProvincia());
                rellenaTabla(jfDni.getText());
            } else {
                VentanaNotificaciones.ventanaError("PROPIETARIO NO EXISTE", padre);
            }
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
        }
    }//GEN-LAST:event_jfDniFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        /**
         * Permite que la ventana principal sea visible 
         */
        padre.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        /**
         * Permite que la ventana principal sea visible 
         */
        padre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        /*
        Este boton limpia todos los textField con la tabala e incializa a otro propietario 
        */
        limpiaTabla();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbElimVehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbElimVehiActionPerformed
        try {
            /**
             * Este boton elimina los vehiculos del propieatario comprovando que exista luego limpiara la pantalla 
             * y lanzara true en la variable booelan flag que permitira eliminar al propietario
             */
            jbElimVehi.requestFocus();
            n = DataBaseSegura.eliminarVehiculo(p.getDni());
            if (n != 0) {
                VentanaNotificaciones.ventanaOK("VEHICULOS ELIMINADOS", padre);
                limpiaTabla();
                flag = true;
                n = 0;
            }
            if (p == null) {
                VentanaNotificaciones.ventanaError("NO HAY NINGUN PROPIETARIO SELECCIONADO", padre);
            }
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
        } catch (NullPointerException e) {
            VentanaNotificaciones.ventanaError("NO HAY NIGUN PROPIETARIO SELECCIONADO", padre);
        }
    }//GEN-LAST:event_jbElimVehiActionPerformed

    private void jbEliminarPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarPropActionPerformed
        try {
            /*
            Si el propietario no es nulo y la variable flag es true osea que no el propietario no tiene vehiculos permitira eliminar al propietario
            lanzando todos los errores que puedan existir
            */
            jbEliminarProp.requestFocus();
            if (p != null) {
                if (flag == true) {
                    j = DataBaseSegura.eliminarPropietario(p.getDni());
                    if (j != 0) {
                        VentanaNotificaciones.ventanaOK("PROPIETARIO ELIMINADO", padre);
                        limpiaTabla();
                        limpiaPantalla();
                    } else {
                        VentanaNotificaciones.ventanaOK("FALLO ALGO LLAME AL INFORMATICO", padre);
                    }
                } else {
                    VentanaNotificaciones.ventanaError("SOLO SE PUEDE ELIMINAR PROPIETARIO SI NO TIENE NINGUN VEHICULO", padre);
                }
            }
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), padre);
        }
    }//GEN-LAST:event_jbEliminarPropActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbElimVehi;
    private javax.swing.JButton jbEliminarProp;
    private javax.swing.JButton jbVolver;
    private javax.swing.JTextField jfDni;
    private javax.swing.JTable jtTablaVehiculos;
    private javax.swing.JTextField tfApeliido;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfProvincia;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
    /**
     * Este metodo recive el dni del propietario luego ejecuta el metodo de la clase BaseDataSegura que permite sacar la lista de vehiculos que tiene 
     * el propieatario si no tiene ninguno se lanza el mensaje y si los tiene rellenara la tabla con los vehiculos
     * @param dni
     * @throws MyError 
     */
    private void rellenaTabla(String dni) throws MyError {
        DefaultTableModel tabla = (DefaultTableModel) jtTablaVehiculos.getModel();
        listaVehiculos = DataBaseSegura.listaVehiculosPro(dni);
        if (listaVehiculos.isEmpty()) {
            VentanaNotificaciones.ventanaOK("No tiene vehiculos registrados", padre);
            flag = true;
        } else {
            for (Vehiculo v : listaVehiculos) {
                tabla.addRow(v.toArray());
            }
        }
    }
/**
 * limpia la tabla 
 */
    private void limpiaTabla() {
        DefaultTableModel modeloTabla = (DefaultTableModel) jtTablaVehiculos.getModel();
        while (modeloTabla.getRowCount() >= 1) {
            modeloTabla.removeRow(0);
        }
    }
    /**
     * Limpia todos los JTextField e inicializa a un nuevo propietario
     */
    private void limpiaPantalla() {
        tfApeliido.setText("");
        tfNombre.setText("");
        tfProvincia.setText("");
        tfTelefono.setText("");
        jfDni.setText("");
        p=new Propietario();
    }
}
