/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazG;

import Modelo.DataBaseSegura;
import Modelo.Propietario;
import controlador.MyError;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alumno
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jbAñadirVe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbListaVehiculos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbListaProp = new javax.swing.JButton();
        jbExportar = new javax.swing.JButton();
        jbSalor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("BIENVENIDO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jbAñadirVe.setText("Añadir Vehiculo");
        jbAñadirVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAñadirVeActionPerformed(evt);
            }
        });

        jButton1.setText("Añadir Propietario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbListaVehiculos.setText("Lista Vehiculos");
        jbListaVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaVehiculosActionPerformed(evt);
            }
        });

        jButton2.setText("Baja Propietario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jbListaProp.setText("Lista Propietario");
        jbListaProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaPropActionPerformed(evt);
            }
        });

        jbExportar.setText("Exportar");
        jbExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExportarActionPerformed(evt);
            }
        });

        jbSalor.setText("SALIR");
        jbSalor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel2.setText("CONCESIONARIA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jbAñadirVe)
                    .addComponent(jbListaVehiculos)
                    .addComponent(jButton2)
                    .addComponent(jbListaProp)
                    .addComponent(jbExportar)
                    .addComponent(jbSalor))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAñadirVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbListaVehiculos)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbListaProp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbExportar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSalor)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAñadirVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAñadirVeActionPerformed
        VentanaAñadirVehiculo v = new VentanaAñadirVehiculo(this);
        setVisible(false);
    }//GEN-LAST:event_jbAñadirVeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaAñadirPropietario p = new VentanaAñadirPropietario(this);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbListaVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaVehiculosActionPerformed
        try {
            ArrayList listaVehiculos = DataBaseSegura.consultaVehiculos();
            if (listaVehiculos.size() > 0) {
                VentanaListaVehiculos lv = new VentanaListaVehiculos(this);
                setVisible(false);
            }
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), this);
        }
    }//GEN-LAST:event_jbListaVehiculosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VentanaBajaPropietario c = new VentanaBajaPropietario(this);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            System.exit(0);
            DataBaseSegura.cerrarConexion();
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), this);
        }
    }//GEN-LAST:event_formWindowClosed

    private void jbListaPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaPropActionPerformed
        try {
            ArrayList<Propietario> p = DataBaseSegura.listaPropietariosSolos();
            VentanaListaPropietarios s = new VentanaListaPropietarios(this, p);
            setVisible(false);
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), this);
        }
    }//GEN-LAST:event_jbListaPropActionPerformed

    private void jbExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExportarActionPerformed

        try {
            ArrayList listaVehiculo = DataBaseSegura.consultaVehiculos();
            ArrayList listaPropietarios = DataBaseSegura.listaPropietariosSolos();
            VentanaExportarXML xml = new VentanaExportarXML(this, listaVehiculo, listaPropietarios);
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), this);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jbExportarActionPerformed

    private void jbSalorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalorActionPerformed
        System.exit(0);
        try {
            DataBaseSegura.cerrarConexion();
        } catch (MyError ex) {
            VentanaNotificaciones.ventanaError(ex.getMessage(), this);
        }
    }//GEN-LAST:event_jbSalorActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAñadirVe;
    private javax.swing.JButton jbExportar;
    private javax.swing.JButton jbListaProp;
    private javax.swing.JButton jbListaVehiculos;
    private javax.swing.JButton jbSalor;
    // End of variables declaration//GEN-END:variables
}
